#!/bin/bash

FUNC=$1

func() {
  git show home-bin/common-functions:$FUNC > $FUNC || exit 1
}

if [ -z "$FUNC" ]; then
  git remote add home-bin https://github.com/axet/home-bin.git || exit 1
  git fetch home-bin || exit 1
  func common-functions-merge || exit 1
else
  func $FUNC || exit 1
fi
